# Generated by Django 3.1.3 on 2021-01-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
